# Generated by Django 4.2.3 on 2023-08-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cover',
            field=models.ImageField(blank=True, default='', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time_unit',
            field=models.CharField(choices=[('Minutes', 'Minutes'), ('Hours', 'Hours')], max_length=65),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings_unit',
            field=models.CharField(choices=[('Cups', 'Cups'), ('Slices', 'Slices'), ('Pieces', 'Pieces')], max_length=65),
        ),
    ]
